apiVersion: 1

datasources:
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    url: http://localhost:3000
    jsonData:
      authType: default
      defaultRegion: us-east-1
    secureJsonData:
      accessKeyId: ${AWS_ACCESS_KEY_ID}
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    isDefault: true
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: false
    editable: true
